# Site settings
baseURL = "https://levitanong.com/"
# themesDir = "../.."
languageCode = "en-us"
title = "Levi Tan Ong's Blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
staticDir = "static"
# Disable comments by leaving disqusShortname empty
# disqusShortname = "spf13"
#
# pygmentsUseClassic = true
pygmentsCodefences = true

[pygmentsOptions]
	noclasses = true

[params]
	name = "Levi Tan Ong"
	description = "Code and Stuff"
	bio = "Full Stack Developer, Lisp Enthusiast, Reluctant Designer"
	# Enter optionally your twitter account
	twitter = "https://twitter.com/levitanong"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom.css", "css/syntax.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a full stack developer. In danger of turning Emacs into my OS."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
	# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
	socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
	twitter  = "https://www.twitter.com/levitanong"
	# facebook = "https://www.facebook.com/"
	github   = "https://www.github.com/levitanong"
	# dribble  = "https://www.dribbble.com/"
